import fs from 'fs';

const rawText = `PROGRAMME FOR THE AWARD OF HONORARY DEGREES, CONFERMENT OF DEGREES AND AWARD OF DIPLOMAS AND CERTIFICATES OF BREAKTHROUGH BIBLE UNIVERSITY ON FRIDAY, 4TH DECEMBER, 2020

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY HONORARY DOCTORATE DEGREES

NO	NAME	TITTLE
1	DANIEL KITHIA M’ARIMBA	DOCTOR IN  SACREDMINISTRY
2	EPHANTUS MAHINDA THUKU	DOCTOR IN HUMANE LETTERS
3	GABRIEL NG’ANG’A MATHU	DOCTOR IN SACRED MINISTRY
4	JOHN HIUHU GITITU	DOCTOR IN DIVINITY
5	ANNE MUKUHI GABRIEL MICHIRA	DOCTOR IN HUMANE LETTERS
6	CHARLSE ELKANA MICHIRA	DOCTOR IN HUMANE LETTERS
7	DAVID KIBUCI ICIKA	DOCTOR IN DIVINITY
8	PAUL M MUTHOTHO	DOCTORATE IN SACRED LEADERSHIP
9	MOSES KWERI KINYA	DOCTOR IN  SACRED MINISTRY 
10	EUNICE MUTHONI KABUI	DOCTOR IN HUMANE LETTERS
11	GORDON ARJAAN VAN VEELEN	DOCTOR IN DIVINITY
12	JEMIMA NJAMBI GICHUNGU	DOCTOR IN HUMANE LETTERS
13	JOHN MWANGI WAWERU	DOCTOR IN HUMANE LETTERS
14	JOSEPH NGACHA KARANI	DOCTOR IN HUMANE LETTERS
15	PAUL ODHIAMBO AMADI	DOCTORATE IN SACRED LEADERSHIP
16	PETER MUHIA NGA’NG’A	DOCTOR IN HUMANE LETTERS
17	SAMUEL THIONG’O MWANGI	DOCTOR IN HUMANE LETTERS
18	SAMUEL WAITHAKA MWANGI	DOCTORATE IN SACRED LEADERSHIP
19	SIMON NG’ANG’A KING’ARA	DOCTOR IN HUMANE LETTERS
20	JACKSON KIPKEMOI KOSGEI	DOCTORATE IN DIVINITY
21	KIPKOECH KIPTOO KIBET	DOCTORATE IN SACRED LEADERSHIP
22	MICHEAL NGUGI KARANJA	DOCTOR IN HUMANE LETTERS
23	LUCY WANGARI WAMBUGU	DOCTOR OF HUMANE LETTERS
24	RICHARD MAINA KAMAU	DOCTORATE IN DIVINITY
25	ROSA JERUTO KOSKEI	DOCTORATE IN DIVINITY
26	SAMUEL WAWERU KARIUKI	DOCTORATE IN MINISTRY
27	EZEKIEL WAITHAKA MUIRURI	DOCTORATE IN DIVINITY
28	MOSES KWERI KINYA	DOCTORATE IN DIVINITY
29	JANE MUREITHI	DOCTOR IN HUMANE LETTERS
30	PETER KINARI  KIHARA	DOCTOR IN HUMANE LETTERS
31	VEN HABIL NAKHUMWA	DOCTOR IN HUMANE LETTERS
32	SAMUEL  OTIENO NGONDE	DOCTOR IN  SACRED LEADERSHIP
33	SIMON MWAURA WAMWEA	DOCTOR IN HUMANE LETTERS
34		




NAIROBI COUNTY STUDENT (PROF: DR PATRICK NJUGUNA GACHERU)
PHD IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAMES
1	EVANS KEITANY CHEPKWONY
2	ELIJAH NG’ANG’A NJOKI
3	FRANCIS WACHIRA GACHERU
4	FREDRICK MUSAU MULI
5	GEORGE OWITI AWILI
6	JANE NJERI KINYANJUI
7	JOSEPH KIITI MUTUA
8	GIDEON SILA KING’OO
9	RUMISHAELI OBED LYIMO
10	JOSEPH MAITHIA NZOMO
11	SIMON K KARANJA
12	AGNES AMADI
13	ROBERT THAWI







BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAROK COUNTY STUDENTS(PROF:ELIJAH NG’ANG’A NJOKI)
MASTERS IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAME
1.	JOSEPH KAREMERI WANJIRU


BACHELORS DEGREE IN BIBLE & THEOLOGY
NO	NAMES
1	ALBERT KIHARA GICHURU

2	JOHN KAMAU NGUNGA

3	SAMUEL MOONKA

4	SAMWEL TEEKA

5	CHRISTINE WAMBUI TOROME

6	GEORGE TOROME

7	GRACE WANJIKU KAREMERI

8	SIMON SANKALE NJOROGE

9	HOSEA NJOROGE IRUNGU

10	CHARLES LETUYA MUCHENDU

11	JAMES IRUNGU MURIGI



BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAIROBI COUNTY UTAWALA STUDENTS(PROF: JOSEPH MAITHIANZOMO)
DIPLOMA IN THEOLOGY
NO	NAMES
1	HOSEA  GITONGA
2	ROBERT KAMWALO
3	LUCY KOKONYO
4	JANET WANJIKU
5	EASTHER MITCHEL
6	SCHOLASTICANYAMBURA
7	RUFUS NYANGA
8	CATHERINE IRERI

DIPLOMA IN COUNSELING PSYCHOLOGY
NO	NAMES
1	MARK MATIVO
2	HOSEA  GITONGA
3	ROBERT KAMWALO
4	LUCY KOKONYO
5	JANET WANJIKU
6	EASTHER MITCHEL
7	SCHOLASTICANYAMBURA
8	RUFUS NYANGA
9	CATHERINE IRERI







BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
KAJIADO COUNTY STUDENTS(PROF: JOSEPH MAITHIANZOMO)
BACHELORS IN LEADERSHIP
NO	NAMES
1	SAMUELMONIREL
2	RAPHAEL  NYAKUNDI
3	BERNARD  MUIA
4	JOSHUA K WAITITU
5	DOUGLAS KULEI
6	PHILIP  KOITEE
7	KENNEDY  KISENYA
8	CLEMENT WAMBARI
9	JACKSON  POLONG
10	JOHN W MATHU
11	MARTIN M FAVOR
12	JULIUS MUISU MUTETI

BACHELORS IN THEOLOGY
NO	NAMES
1	FRANCIS K MPINDAKI
2	ELIJAH  KAPORO
3	JEREMIAH NKIMINIS
4	JUSTINE T MUNYOKI






BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
KAJIADO COUNTY STUDENTS(PROF: JOSEPH MAITHIANZOMO)
DIPLOMA IN LEADERSHIP
NO	NAMES
1	ROSE MUSYOKA
2	MELODYKONGU
3	DANIEL KYULE
4	PETERSON MBAE
5	ANTONY KINYANJUI
6	FAITH MUTUKU
7	PAULINE MUENI DAVID
8	ANDREW WAWERU
9	KENNEDY NGULA
10	SOLOMON KIRUMPAS
11	AGNES N JAPHETH
12	PHILIP M KILONZO
13	PATRICK MUMO

DIPLOMA IN THEOLOGY
NO	NAMES
1	MELODY KONGU
2	DANIEL KYULE
3	PETERSON MBAE
4	ANTONYKINYANJUI
5	FAITH MUTUKU
6	ANDREW WAWERU
7	KENNEDY NGULA
8	SOLOMON KIRUMPAS
9	PHILIP M KILONZO
10	PATRICK MUMO
11	TITUS K MUTUA

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAIROBI/MURANGA COUNTY STUDENTS(PROF:SIMON K KARANJA)
NAIROBIINTRODUCTION TO THEOLOGICAL STUDIES
NO	NAMES
1	ROSE MUTHAKA KABURA
2	FREDERICK OTIENO ODUNGA
3	SUSAN KAVUTHA MUTUA
4	ALLAN KARIUKI KANGACA
5	JOSPHAT NYAGA KAMWETI
6	LUCY MWIHAKI NGERE
7	EPHANTUS MUIGA MAINA
8	DAVID OMBONYO
9	FAITH WAMBUI NGIGI
10	PETER LUKA AHOLI
11	DANIEL THUKU KIMUYU
12	JOSEPHINE MUTHOKI NYAGA MUTUA
13	JACKLINE SYOMBUA MUTUA
MURANGA INTRODUCTION TO THEOLOGICAL STUDIES
NO	NAMES
1	WILLY NDERU KIMANI
2	STPHEN NJOROGE KAARA
3	LYDIA WANGECHI WAHOME
4	DAVID MBOGO MURUNGA
5	HUMPHREY IRUNGU MAINA 
6	JAMES GUCHUA MWANGI
7	RYTH NYAWIRA NJOROGE
8	SAMUEL MAMBO MWANGI
9	JAMES NJOGU MAHIHU
10	LYDIA WANJIKU KIMEMIA
11	HELLEN WANJIKU MWANGI
12	SAMUEL MWANGI WANGARE
BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
TANZANIA KILIMANJAROSTUDENTS(PROF: RUMISHAELI OBED LYIMO)
HIGHER DIPLOMAIN THEOLOGY AND BIBLICAL STUDIES
NO	NAMES
1	BENARD COSMAS
2	DEOGRATIUS MOSHI
3	ELIJAH TAJEU TANIN
4	JAPHERSON SAULI
5	MATHIAS MRITA
6	PERPETUA RABIETH
7	PETRO ABDI MBISE
KILIMANJARO CERTIFICATE IN THEOLOGY AND BIBLICAL STUDIES
NO	NAMES
1	ABEL JOSEPH NGOWI
2	CHARLES MLAKI
3	ISACK KAAYA
4	LIDA LYIMO
5	NEEMASAFINA MSANGI
6	OSMUNDA JLYIMO
7	NEEMA DANIEL
8	JAMES MBISE
ARUSHA CERTIFICATE INTHEOLOGY AND BIBLICAL STUDIES
NO	NAMES
1	ANGELA DAUDI
2	ERCA WILLIAM
3	ESTHER ELIMELECK LYIMO
4	FLORA MRITA
5	HAIKAELI STEVEN
6	CHRISTINA HOSSEN LESHINGO
7	JOYCE MAZIKU
8	MARY KISIMA
9	PAULO KANGAJAKA

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
ILBISILL CAMPUS (KAJIADO COUNTY)(PROF:GIDEON SILA KING’OO)
BACHELOR DEGREE IN THEOLOGICAL STUDIES
NO	                          NAMES
1	CHRISTOPHER MAINA KINUTHIA
2	NKAITOLE OSIAPAI LENANU
3	SAULO PURDUL OLOKUANI

CERTIFICATE IN BIBLE AND THEOLOGY
NO	NAMES
1	ABEDINEGO SARUNI RAMPEI
2	EZEKIEL LEPARAKUO NTINI
3	JOSEPH GICHOHI MWANGI
4	ELIZABETH WANGARE NKIMINIS












BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
WENDANO MATUU STUDENTS (AGNES NDUKU MUNYAO)
BACHELORS DEGREE IN THEOLOGICAL STUDIES
NO	NAMES
1	ELIJAH MUTHIANI THYAKA
2	JULIUS KAKUNDI MULINGE
3	MARGARET MELI KIOKO
4	JONAH MUTUA MWANGANGI

DIPLOMA IN THEOLOGICAL STUDIES
NO	NAMES
1	DALMUS  KATAMBO KASEKI
2	JONAH MUTUA  MWANGANGI
KITUI COUNTY,MWINGI NORTH,GAI CLASS
CERTIFICATE IN THEOLOGICAL STUDIES
NO	NAMES
1	JOHN MBULO  MUSYOKA
2	ROSE NDINDA  MAILU
3	ANNASTACIA  KATHILI MUSYOKA
4	WANZA  NGUMBI
5	PETER MUNEENI MWANGANGI
6	SANFLEX MUISYO  KAVINDU
7	MWIYATHI MUSYA 
8	JAMES MUSYA  NDEME
9	MUSYOKI MUTUNGA
10	CHARLES   MUSYA MUTHEKI 
11	DAVID  KILYUNGI  MUTHENGI 
12	RUTH   KATULULU MUSEMBI 
13	MUTUA NZENGU
14	COSMAS MWINZI MAITHYA
15	JAMES MUSYOKI MUSILI

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
KAJIADO COUNTY STUDENTS(PROF: ROBERT THAWI)
BACHELOR DEGREE IN THEOLOGICAL STUDIES
NO	NAMES
1	IMAN OLE KOISAKA
2	JOSEPH TANTEI SAISA
3	JOSHUA NAKINYI LOIS
4	JULIUS SAIKO TULITO
5	JOEL KARAINE ONING'OI
6	ABRAHAM SIMIREN
7	GEOFFREY KASIMU
8	ELIZABETH  MUTUNKEI
9	EZEKIEL MEKI NKURRUNAH
10	HENRY MWENDA HABILL MNOFU
11	BENARD  PANAI SAMPAO
12	POLOKUA  MURAAYA JOSHUA

DIPLOMA IN THEOLOGICAL STUDIES
NO	NAMES
1	JAMES LARINKOI MUTUNKEI

DIPLOMA IN CHRISTIAN LEADERSHIP
NO	NAMES
1	JACKSON NKONKAT OLE TARAYIA

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAIROBI COUNTY KASARANI STUDENTS (PROF: JANE NJERI KINYANJUI)
MASTERS IN COUNSELING PSYCHOLOGY
NO	NAMES
1	BETH NYAMBURA MWANGI
2	HANNAH NYAMARU NGENDO 
3	DAVID MARONGO KASHI
4	BETH WAMBUI NJUGUNA
5	MARY WAIRIMU NGUGI
6	PRISCILLA MUHONJA  KASHI 
7	MESIYA ODHIAMBO MARENYA
8	HELLEN NDUTA KARUGA 
9	TITUS MUNDIA MWANIKI
10	PRISCAH WACHEKE NDERITU 
11	HANNAH WANJIKU MBUGUA 
12	MARGARET WANJIRU NJUGUNA

DIPLOMA IN COUNSELING PSYCHOLOGY
NO	NAMES
1	MARY WANJIKU NDUNGU
2	DAVID KARANJA NGIGI 
3	MIRIAM WAIRIMU NDUNGU
4	MARGARET WANJIRU GATANGI 
5	VICTOR GACHERU GATHIGIA


BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAIROBI COUNTY KASARANI STUDENTS(PROF: JANE NJERI KINYANJUI)
BACHELOR DEGREE IN COUNSELING PSYCHOLOGY
NO	NAMES
1	JOSHUA MAINA KAGWE
2	SUSAN MUTHONI NZIOKA
3	MWENDWA MAWIA 
4	RUTH KAINDA BARIMBA 
5	KARANJA APOLO SIMON
6	NAOMI NJERI KARANJA 
7	FRASHIA WANJIKU CHEGE
8	PAUL CHEGE MWAURA 
9	MARTHA MUCIKU WAKAYU
10	RICHARD MITAHI WACHIRA











BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
LAIKIPIA CAMPUS STUDENTS (PROF:FRANCIS WACHIRA GACHERU)
BACHELORS DEGREE IN THEOLOGICAL STUDIES
NO	NAMES
1	FRANCIS KINUTHIA KAMAU                                  
2	JOSPHAT MBOKO KAMAU                                    
3	STEVENS MBURU MUIRU                                     
4	JOSEPH MURIITHI KARIMI                                    
5	WINSTON WAIHENYA KIBUCHI                           
6	GRACE MUTHONI KAMAU                                   
7	MIRIAM WACHINGA WAMBUGU                      
8	FRANCIS NDUNGU NJOROGE                               
9	MARGARET WANJIRU KARIUKI                              
10	JOSEPH GITAU UIRU                                              
11	PAUL NGATIA WAHOME                                      
12	DIANA NZIZA MOTOGWA                                    
13	NDIRANGU SAMUEL KARONJI                             

DIPLOMA IN COUNSELLING PSYCHOLOGY

NO	NAMES
1	JOSEPH NDIBA MUTHIORE
2	KABOCHI GRACE MUMBI
3	MAINA JACKSON MWANGI
4	SHUNZA CATHERINE WANGARE





BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
LAIKIPIA CAMPUS STUDENTS (PROF:FRANCIS WACHIRA GACHERU)
DIPLOMA IN THEOLOGICAL STUDIES
NO	NAMES
1	NJOROGE MARGARET NGINA                               
2	 NYAMBURA TRIZAR WANJIRU                         
3	WAMUCII NICHOLUS NYAGI                                
4	ZACHAEUS NJENGA KIRAGU
5	EUNICE NJERI KAMAU                                     
6	GRACE NYAKIO MBUGUA
7	JOSEPH KAMAU MACHARIA
8	NAFTARY KARICHU NJORA
9	NDEGWA EUNICE MUTHONI
10	WAKABA ESTHER NDUTA
11	WAMBAZU MOSES

BACHELOR DEGREE IN COUNSELING PSYCHOLOGY
NO	NAMES
1	RICHARD MUTAHI WACHIRA








BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
ZIMBABWE CAMPUS STUDENTS (PROF:PRINCE TONDERAI TSAWAYO)
DIPLOMA IN THEOLOGICAL STUDIES
NO	NAMES
1	PAULINE MANGEZI
2	AUBREY MAFUKA
3	WARREN GEORGE CHAURURA
4	TSITSI MARGRET SHINDI
5	TASHINGA DAVID NDORO
6	TAPIWA DAWN NDORO
7	GEORGINAH BERNARD
8	CAROLINE CHOKUONA
9	FREDMAN MUNYARADZI
10	KEAKANTSE WILHEMINAH MOKAILA
11	FAITH MUVHUNZI
12	YONDER MARUMOAGAE
13	DANIELDENGU	
14	MELODY GONDO
15	YURINOV MAMBAU
16	ANESU BLESSING NDAWANA
17	SIBUSISIWE NGULUBE
18	MUGOVEWASHE CHISORA
19	MCDONALD LUNGU
20	YURINOV MAMBAU
21	ANESU BLESSING NDAWANA
22	FORTUNATE VHARETA
23	BERNARD MANHENGA




BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
ZIMBABWE CAMPUS STUDENTS (PROF:PRINCE TONDERAI TSAWAYO)
BACHELOR DEGREE IN THEOLOGICAL STUDIES
NO	NAMES
1	ANTHONY NYADINGA
2	ELIJAHMAPISAUNGA
3	IAN CHIDONGO
4	GIBSONNYAMBAYO
5	KABIKAMUZANGA
6	SHEMAHIRWA LEWIS
7	CAUSEMORE MUCHENGETI MASHIPE
8	CLAUDIUS THOLE
9	PATSON   MAZARURA
10	SINOSCHIRIGA
11	RUTENDO CLARIS   PARADZA
12	MILDRED REUBENS SHANGUBO
13	DARREN BOTHA








BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAIROBI COUNTY SAIKA STUDENTS (PROF:JOSEPH KIITI MUTUA)
BACHELOR DEGREE IN COUNSELING PSYCHOLOGY
NO	NAMES
1	JAPHETH MUTEI MUTUA
2	JOSEPH MICHAEL MAINA
3	MASONGO LAMECK NYANGAU
4	GITHUKA PURITY NJERI
5	STEPHEN MUSYOKA KALEMBWA
6	LEAH WANZA MUTUNGA
7	SIMON PETER WAFULA
8	WILFRED IGNATIUS OCHIENG
BACHELOR DEGREE IN BIBLE AND THEOLOGY
NO	NAMES
1	HILARY MAINA GICHUKI
2	JAPHETH MUTEI MUTUA
3	JONES WAFULA OCHIENG
4	SIMON PETER WAFULA
5	JULIUS MWANGE MBATHI
6	WILFRED IGNATIUS OCHIENG
7	BENJAMIN MAINA MUNYIRI




BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAIROBI COUNTY SAIKA STUDENTS (PROF: JOSEPH KIITI MUTUA)
BACHELOR DEGREEIN CHRISTIAN LEADERSHIP
NO	NAMES
1	STELLA NDILA KILONZO
2	JAPHETH MUTEI MUTUA
3	NICHOLAS MUSYOKA MUTUA
4	ANTHONY NDUNG’U MURIGI
5	SIMON PETER WAFULA
6	 JULIUS MWANGE MBATHI
7	LEAH WANZA MUTUNGA
8	JONES WAFULA OCHIENG
9	STEPHEN MAINA GIKIRU
10	WILFRED IGNATIUS OCHIENG
DIPLOMA IN COUNSELLING PSYCHOLOGY
NO	NAMES
1	HANNAH WANJIRU GITHUKA
2	ADHIAMBO SARAPHINE LETTY
3	RHODAH MUNYIVA MAKAU
4	ANTHONY NDUNG’U MURIGI
5	KATAIKE DAPHINE
6	IRENE MUENI MUTEMI
DIPLOMA IN BIBLE AND THEOLOGY
NO	NAMES
1	FRANCIS MULI
2	PAUL GITHUKA NGARUIYA 
3	MICHAEL MUTUA KYENI
4	AMOS MBATHI MWANZIA
DIPLOMA IN LEADERSHIP
NO	 NAMES
1	GIBSON SANDE MUTHANGYA
BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
KIRINYAGA COUNTY KAGIO STUDENTS (PROF: JOSEPH KIITI MUTUA)
CERTIFICATE IN BIBLE AND THEOLOGY
NO	NAMES
1	SIMON MAINA NJIGOYA
2	GEORGE STEPHENSON MURIITHI
3	SIMON CHOMBA WAKABU
4	ELIJAH MURIITHI
5	DANIEL NJOGU GICHOHI
6	FRANCIS MUREITHI GATHENGE
7	ZABLON KIMINDO KIBARA
8	ALICE WANJIRU KIBUCI
9	BETH WANJERI MUIGANA
10	JOHNSON MUCHOKI KARANI
11	BONIFACE WARUI
12	ALBERT MAINA MUTERU
13	KINYUA KIBARIA
14	ALEXANDER NJOGU MBUI
15	SIMON MURIMI JULIA
16	JOSEPH MURAGE MUGO
17	FELISTAR W.GITHII
18	PHINEAS WAWERU
19	JOSHUA WACHIRA
20	JAMES MURIITHI ICIKA
21	JANE NJOKI WACHIRA
22	SAMUEL NJAU KIBANDI
23	MIKE KIGOTHO
24	DAMARIS KIGOTHO
25	SAMUEL MUTHIGANI GICHARIA
26	SOPHIA WAKIO KIBUCI
27	JECINTA WANJIRU  MWANGI
28	THOMAS MUTHII GIKUNJA
29	ISAAC IRUNGU MURAGURI
30	CORNELIUS MWANGI
31	JAMES NJIRU KIMUU
32	JOHN WACHIRA

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
KIRINYAGA COUNTY KAGIO STUDENTS (PROF: JOSEPH KIITI MUTUA)
DIPLOMA IN BIBLE AND THEOLOGY
NO	NAMES
1	DAVID KIBUCI ICIKA
2	ISAAC GICIRA MUCHIRI
3	BENARD NJUGUNA
4	JULIUS MURIMI KIAINDO
5	SIMON WACHIRA KUNGÚ
6	MIKE KIGOTHO 
7	DAMARIS MUMBI 














BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
MAKUENI COUNTY STUDENTS (PROF:JOSEPH MUTUNGA MUTUA)
MASTERS IN PHILOSOPHY OF RELIGION AND APOLOGETIC 
NO	NAMES
1	DUNCAN MUASYA KIMONDIU

BACHELOR DEGREE IN COUNSELING PSYCHOLOGY
NO	NAMES
1	DANIEL MUTHOKA PETER

BACHELORS DEGREE IN BIBLICAL AND THEOLOGICAL STUDIES
NO	NAMES
1	ESTHER MBULA DAUDI
2	SAMUEL MWANIA DAUDI
3	SERAH MWIKALI KIOKO
4	SHERIC MBULA KYENZI

DIPLOMA IN BIBLICAL AND THEOLOGICAL STUDIES
NO	NAMES
1	DENNIS MWENDWA MUSYOKI
2	ROBINSON SIMON MUTUA
3	CECILIA MUENI MUASYA
4	ROSE MBENEKA NZUKI
5	FRANCISCAH NTHENYA JACOB
6	QUEEN NTHENYA MUTUA

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAKURU REGION STUDENTS (PROF: EVANS KEITANY CHEPKWONY)
MASTERS IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAMES
1	RACHEAL AMUNZE WAMBEYI
2	PAMELA NGESA OWINO 
3	JOHN NAMUKURU WAMWOMA   
4	JECINTA WAITHERERO MWAGO.
5	FRANCIS MONANTI AKANGA
6	GILBERT KIPKOSGEI KURGAT 
7	EUNICE MIGIDE MFWOGO.
8	ROSEMARY MACHARIA. 
9	SUSAN NYAMBURA MACHARIA
10	SAMMY KIPCHOGE CHELUGO 
11	HELLEN WANJERU MUSYOKA
12	MATTHEW MUSYOKA NTHIWA
MASTERS IN THEOLOGICAL STUDIES
NO	NAMES
1	FRANCIS MONANTI AKANGA
2	MATTHEW MUSYOKA NTHIWA
BACHELORS IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAMES
1	ELIJAH KIMANI MWAURAH    
2	 ELIJAH GATAMA MUCURI 
3	 DAVID NJOROGE WANJIKU 
4	JOSEPH MBUGUA WAIRIMU 
5	CHARLES LWABI MUSIA
6	JULIUS KIPKURUI CHEMNJOR 
7	ZACHARIA SOROM ADOMONG’URA
8	RICHARD KIPTISIA TUIKONG
9	ISAIAH MURIATHI ANDREW. 
10	JAMES GACHIE GATHIRI
11	REBECCA KWAMBOKA MOSOTI. 
12	ISAAC NJENGA KAMAU 
13	RACHEAL WANJIKU MUIGAI
BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAKURU REGION STUDENTS (PROF: EVANS KEITANY CHEPKWONY)
BACHELORS IN THEOLOGICAL STUDIES
NO	NAMES
1.	RACHEAL AMUNZE WAMBEYI
2.	PAMELA NGESA OWINO 
3.	JOHN NAMUKURU WAMWOMA   
4.	JECINTA WAITHERERO MWAGO.
5.	FRANCIS MONANTI AKANGA
6.	GILBERT KIPKOSGEI KURGAT 
7.	SUSAN NYAMBURA MACHARIA
8.	SAMMY KIPCHOGE CHELUGO 
9.	ELIJAH KIMANI MWAURAH    
10.	 ELIJAH GATAMA MUCURI 
11.	 DAVID NJOROGE WANJIKU 
12.	JOSEPH MBUGUA WAIRIMU 
13.	CHARLES LWABI MUSIA
14.	JULIUS KIPKURUI CHEMNJOR 
15.	ZACHARIA SOROM ADOMONG’URA
16.	RICHARD KIPTISIA TUIKONG
17.	ISAAC NJENGA KAMAU 
18.	HELLEN WANJERI MUSYOKA. 
19.	GRACE KARUIRU. 
20.	ALBERT KAISHA KIVAIRO 
21.	RACHAEL WANJIKU MUIGAI.
22.	LAWRENCE KARANI SILAS 
23.	DORCAS JEBET KIUNGA 
24.	SUSAN ATIENO   OPIYO,
25.	LUCAS MUSYIMI NZIOKA. 
26.	CHRISTOPHER NICOLUS MUDIBO
27.	MIRIAM JERUTO KOMEN 
28.	DAVID TWANGA LANGAT
29.	ESTHER TOROITICH 
30.	MATTHEW MUSYOKA NTHIWA
31.	SAMWEL BOGONKO MOKOYA

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAKURU REGION STUDENTS (PROF: EVANS KEITANY CHEPKWONY)
DIPLOMA IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAMES
1.	ALEXANDER KIPSANG MOI 
2.	PAUL KIPKURUI NGENO 
3.	NATHAN KIPSANG KOECH
4.	SAMUEL RONO 
5.	EMMANUEL KIPKORIR BUSIENEI 
6.	ALICE CHEROTICH RUTTOH
DIPLOMA IN THEOLOGICAL STUDIES
NO	NAMES
1.	PETER NJOROGE KINUTHIA 
2.	PAUL MWANGI GATUNE 
3.	LINET ALIJAH KERUBO 
4.	CALEB WANYONYI BANDA JOHN 
5.	HEZBORN NYANTENGA ONDIMA
6.	CELESTINE  CHEMTAI NDEGE 
7.	LINAH ONGACH
8.	BEATRICE IMINZA ODONGO 
9.	MARY WAHU GACHEMBA 
10.	FREDRICK WERE OKOTH 
11.	DICKSON ORIMBO ADONGO
12.	JANE ACHIENG OGWENO  
13.	BEATRICE GACHEMBA KEORO 
14.	NANCY ADUVUKHA IMBUGWA 
15.	DOMINIC NDUGUYA THEURI 
16.	GEORGE OCHIENG MBEYA, 
17.	FLORENCE KHUYA NYANGWESO, 
18.	ANN WAITHERA GICHUKI. 
19.	NJOROGE JAMES KARIUKI. 
20.	WANGU NEWTON KARANI.
21.	MUNGA PAUL GITHINJI. 
22.	MWAURA SHADRACK KIMARI 
23.	WAITHIRA BEATRICE WANJIRU
24.	MUGO ELIUD MATHENGE
25.	MKOBERO JOHN MUSA 
26.	MAINA SAMSON MWANGI 
27.	MAINA GEOFREY KAMAU  
28.	JOSPHAT MUIGU KAMAU 
29.	ANN WARINGA KIARIE 
30.	NJOROGE PAUL MBURU 
31.	NJOROGE JOSEPH NDING'URI 
32.	MWANGI FRANCIS GITIMU 
33.	MWANGI MILKA NJOKI 
34.	CHEGE JOHN 
35.	IRUNGU ELIUD KAREGA 
36.	FRANCIS MWANGI GITIMU 
37.	JAMES MUNYANYI NJENGA. 
38.	PATRICK OLE SAILEILEL. 
39.	JOSHUA MUNYAO MULE 
40.	IRENE MUKAMI JOSHUA 
41.	DANIEL NYAOGA MOTARI. 
42.	JOSEPH PARSALOI KUYA 
43.	IRENE NJERI GACUBE  
44.	SAMUEL MATEYIAN SAKARA 
45.	JOHN OTIENO OYANDO 
46.	JULIUS LENTOI PERE. 
47.	LERIONKA TINGISHA. 
48.	PETER GITONGA NJUGI. 
49.	EUNICE KATUNGE NZYOKI. 
50.	WESLEY KIPLANGAT BETT. 
51.	JOSHUA KOMEN BUNDOTICH 
52.	VERONICAH J. KOMEN 
53.	JOHN KIPKOECH TAPLOTIN 
54.	BARMASAI KIPGETICH KOECH 
55.	CATHERINE JEPKOECH   KIYENG
56.	RICHARD RETETI SAKARA 
57.	RICHARD ONSONGO NYANG'WONO
58.	 JACKSON RIAMET DAPASH 
59.	SOLOMON  SERETU NCHOSHOI
60.	JAMES NYARIKI MAGOMA
61.	HENRY ODERI
62.	SAAYA JOSPHAT ROKONKA
63.	TITUS MARU KEMEI
64.	LEVI'S NDUNGU MUIGAI
BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAKURU REGION STUDENTS (PROF: EVANS KEITANY CHEPKWONY)
CERTIFICATE IN THEOLOGICAL STUDIES
NO	NAMES
1.	ALEX ACHAYO ANDAKO, 
2.	STANCY KAREN NYANGWESO, 
3.	ROSEMARY DODO, 
4.	JOSEPH CHEPKONGA KASES, 
5.	LILY  AENGWO   
6.	MARY  JEPKEMOI TALLAM 
7.	TIMOTHY KOTOL IKAALE 
8.	MIKE KIPKORIR TANUI 
9.	HELLEN CHEPCHIRCHIR SAMBU 
10.	DAN MINYA NYANGOKA AHAB
11.	MICHAEL BIWOT SONGOL 
12.	JUDY JEPKOECH MATIROR 
13.	ROSA JERUTO KOSKEI 
14.	WINNIE JEPKOSGEI KIPTOO 
15.	ABICAEL  JELIMO KOECH 
16.	SYLVESTER KIPKORIR KANGOGO 
17.	MARY WAHU GACHUMBE
18.	IRENE KERUBO
19.	JOEL YEGON KIPKEMEI
20.	BEATRICE ADHIAMBO
21.	HENRY KISANYA TENDE
22.	FRANCIS KANGETHE KINYANJUI
23.	LILIAN NALASHI OCHIENG
24.	ANN WAIRIMU WACHIRA
25.	SARAH PRISCAH OROTSO
26.	SIMON ONYANGO OLANDO
27.	FREDRICK OTIENO OLOO

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAIROBI COUNTY UTAWALA STUDENTS (PROF:DR PATRICK NJUGUNA GACHERU)
BACHELORS DEGREE IN THEOLOGICAL STUDIES
NO	NAMES
1.	CHARLES ELKANA MICHIRA.
2.	ANNE MUKUHI GABRIEL  MICHIRA
3.	DAVID NJERU EZEKIEL
4.	FRANCIS MUSYOKI WAMBUA
5.	JANE WAIRIMU MUREITHI
6.	PETER NJOROGE MUTURI
7.	AQUINAS WACHIRA MIMANO
8.	SARAH MBUIYU KAMAU
9.	SIMON M. NZUNA
10.	WALI HANNINGTON
11.	AGNES NDUKU MUNYAO

MASTERS DEGREE IN CHRISTIAN MINISTRY  
NO	NAMES
1.	CHARLES ELKANA MICHIRA.
2.	ANNE MUKUHI GABRIEL  MICHIRA
3.	DAVID NJERU EZEKIEL
4.	FRANCIS MUSYOKI WAMBUA
5.	JANE WAIRIMU MUREITHI
6.	
7.	AQUINAS WACHIRA MIMANO
8.	SARAH MBUIYU KAMAU
9.	SIMON M. NZUNA
10.	WALI HANNINGTON
11.	AGNES NDUKU MUNYAO










BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
ETHIOPIA CAMPUS STUDENTS (BISHOP OCHUDHO OMOT)
MASTERS OF CHRISTIAN COUNSELING PSYCHOLOGY
NO	NAMES
1	OPIEW OKUNY  
2	OPIEW OLENY 

MASTERS OF CHRISTIAN ENTREPRENEURSHIP
NO	NAMES
1	OKWOM OJWATO 
2	PHILEMON OPAP 

MASTERS OF CHRISTIAN WORLD RELIGIOUS
NO	NAMES
1	OCHUDHO OMOT OCHANG 

BACHELOR OF CONFLICT MANAGEMENT SKILL
NO	NAMES
1	LIM ABEL 
2	OJULU ACHAW 

BACHELOR OF CHRISTIAN LEADERSHIP AND MANAGEMENT SKILL
NO	NAMES
1	OMOD OCHALLA ABALLA 




BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
KIRINYAGA COUNTY STUDENTS (PROF:FREDRICK MUSAU MULI)
BACHELOR DEGREE IN BIBLE AND THEOLOGY
NO	NAMES
1	HELLEN MUTHEU SIMON
2	SUSAN NYAKIO NJOGU
3	BONIFACE MURIMI MWANIKI
MACHAKOS COUNTY ATHI RIVER CAMPUS
BACHELOR DEGREE IN BIBLE AND THEOLOGY
NO	NAMES
1.	AGNES MUMBUA ZACK
2.	ZACK ARTHUR ONGUKO
3.	SAMUEL WAMBUA MAKEWA
4.	JULIUS MUTUA MBINE
5.	TITUS MWENDWA KATINGU
6.	STEPHEN KISANGULA MULEI
7.	HENRY TIPAPE MEIKAN
8.	BONIFACE MUANGE MBITHI
9.	PATRICK MAAKE SITERU
10.	THOIMASI LEPAPA ADRIAN
DIPLOMA IN BIBLE AND THEOLOGY
NO	NAMES
1.	ANGELINA SYOMITI KIARIE
2.	MARY NJOKI MULWA
3.	ANN WANZA MUTAMBUKI
4.	MARY MUGURE WAWERU
5.	AGNES DORCAS MBENEKA MBITHI
6.	DORIS NDANU MWALIMU
7.	MARY NTHENYA NZEKI
8.	PETER M KISUI 

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
MAGADI STUDENTS (PROF:FREDRICK MUSAU MULI)
DIPLOMA IN BIBLE AND THEOLOGY
NO	NAMES
1	JEREMIAH S KOITUMET
2	MATHEW M LESHAO
3	MIARON OLE KUDATE
4	MPAYIAI NINA
5	LESHINKA OLE SANARE















BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NAIROBI UTAWALA -(PROF:DR PATRICK NJUGUNA GACHERU)
BACHELOR DEGREE IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAMES
1	ELISHA MAGHERE NEHEMIA
2	MURENGA NABUDUWA STELLA
3	SAMUEL WAITHAKA MWANGI
4	SAMUEL  OTIENO NGONDE
5	LUCY WANGARI WAMBUGU
6	WILLIAM GITHINJI WACHIRA

BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
NYANDARUA COUNTY STUDENTS(SUSAN KURIA (JOY))
MIHARATI (AKORINO CLASS)
CERTIFICATE IN THEOLOGICAL STUDIES
NO	NAMES
1.	FRANCIS KIMANI NJOROGE
2.	ELIJAH THUO KARANJA
3.	JOSEPH MWANGI MURIUKI
4.	JOSEPH NJOGU NDERI
5.	STEPHEN KIHIA WANGENYE
6.	JOEL KIIRU GATIMO
7.	ALICE WANJA MWANGI
8.	JOSEPH MWANGI KIMANI
9.	PETER KAHURA MWANGI
10.	JOSEPH MWARIRI GICHIAH
11.	FRANCIS MUORIA NGARUIYA
12.	JESSE WAIHENYA GATI
13.	SAMUEL NJOGU WAITARA
14.	JOSEPH WAITHAKA KURIA
15.	HOSEA ZAKARIA MWARIRI
16.	ANN WAGUTHII MURIITHI
17.	LOISE NJERI KAGIKA 



BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
ETHIOPIA STUDENTS-ADDIS ABABA CAMPUS(PROF: ZERAI HAGOS)
MASTERS IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAMES
1	YISHAK ASSEFA ZERGAW  
2	TEKESTE ALEMAYEHU  MENGESHA 
3	KIDIST ABIY WOSSENU 
4	ABENEZER ANIMUT BEKELE 
5	GETNET NIGUSSIE CHERIE 
6	YOHANES ZEKARIYAS ALEMAYEHU 
7	HIRUT BELACHEW LEGESSE 
8	AYNALEM ALEMAYEHU MAMO 
9	LEMLEM TILAHUN RUFO 

BACHELOR DEGREE IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAMES
1	SAMSON KINFE SIME 
2	MULUBESIRAT TAMERAT  SEDORE







BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
KARUMANDI CAMPUSSTUDENTS(PROF: MOSES KAREITHI MAINA)
BACHELOR DEGREE IN BIBLICAL COUNSELING PSYCHOLOGY
NO	NAMES
1	DAVID CHOMBA GATIMU 
2	EDITH WAWIRA GACHOKI 
3	FRANCIS MUCHIRA KARINGI
4	CAROLINE WAWIRA  GITARI
5	MATARA NYANDWARO LEONARD 
6	MARY WANJIRU MURIITHI
7	REBECCA NJERI NGARI
8	MOSES KAREITHI MAINA
9	LAWRENCE NGARI NGONDI 
10	JAMES KINYUANJUI NGARA

BARCHELOR DEGREE IN LEADERSHIP
NO	NAMES
1	PHYLLIS KARIMI NGARI







BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
HAITI CAMPUS STUDENTS (PROF: ,,,,,,,,,,,,,,,,,,,,,,,,,,,,)
MASTERS IN SYSTEMATIC THEOLOGY
NO	NAMES
1	MICHEL PHANOR
2	ANGELO BONANGE

MASTER DEGREE IN EDUCATION SCIENCES AND LEADERSHIP
NO	NAMES
1	DESIR MICHAEL C.O JONATHAN
BACHELOR DEGREE IN THEOLOGY
NO	NAMES
1	RICARDO MÉRIZIER 
2	RYCK HARTMAN 
3	JOSEPH LOUISSAINT NADÈGE
4	ALEXANDRE LUCSON
5	BELZOR DIEUBON
6	CARL ERIC VILFORT
7	FRANCILLON BARREAU
8	ALY ROSTY
9	GEORGE JEAN BAPTISTE 
10	JEAN LAROSE MYTHIL
11	PIERRE LOUIS EMMANUEL




BREAKTHROUGH INTERNATIONAL BIBLE UNIVERSITY
HAITI CAMPUS STUDENTS 
GRADUATE DIPLOMA IN PASTORAL MINISTRY
NO	NAMES
1	CHÉRY JEANTY 
2	DÉRISMÉ RÉMY
3	LAURENT MARCIAL 
4	LUXAMA WATSON 
5	JULES EMMANUEL
6	VARISTE MACKENSON
7	MICHEL CAMELOT 
8	BENJAMIN TURENNE PATRICIA 
9	PIERRE JEAN MONFRED
10	FRADEUS JOCELYN 
GRADUATE DIPLOMA IN LEADERSHIP AND ADMINISTRATION
NO	NAMES
1	PIERCILUS DÉSIR
2	JEAN LOUIS EMMANUEL 
3	PERRILUS CALUS
4	CHARLES CÉBIEN
HONORIS CAUSA DOCTORATE
NO	NAMES
1	DESIR GABINA EUCHERA`;

fs.writeFileSync('./raw_2020.txt', rawText);
console.log('Saved raw_2020.txt');
